### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by kszcode** [sindresorhus/read-pkg#11]
There seems to be a compilation issue.
If I take out ...option, then it works.
Also probably could be fixed by iterating over it.

```
time npx cypress run
The function exported by the plugins file threw an error.

We invoked the function exported by `<localProjectPath>/tests/e2e/plugins/index.js`, but it threw an error.

 <localProjectPath>/node_modules/read-pkg/index.js:13
		...options
		^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (<localProjectPath>/node_modules/@vue/cli-service/lib/Service.js:5:17)
    at Object.<anonymous> (<localProjectPath>/node_modules/@vue/cli-service/lib/Service.js:424:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (<localProjectPath>/node_modules/@vue/cli-service/webpack.config.js:7:19)
    at Object.<anonymous> (<localProjectPath>/node_modules/@vue/cli-service/webpack.config.js:14:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
        6.89 real         4.69 user         1.10 sys
```

**Comment by sindresorhus** [comment]
I don't know what you're using, but it has to support object-spread syntax. Open an issue on the project you're using instead.
